SUPABASE_URL = "https://ieodzygauglvdkendvmj.supabase.co"
SUPABASE_KEY = "sb_publishable_YS3LTJInGQZgxw0cZmTCZw_4rFz1Oaq"
OPENWEATHER_API_KEY = "2762051ad62d06f1d0fe146033c1c7c8"
SENTINEL_CLIENT_ID = "sh-a2dc43c4-27e5-4472-86f9-ee6d163b757c"
SENTINEL_CLIENT_SECRET = "JPPVjrRsSkqdWpOkKxAJow9t2IKfPbir"

