OPENWEATHER_API_KEY="TU_API_KEY"
SUPABASE_URL="TU_URL_SUPABASE"
SUPABASE_KEY="TU_KEY_SUPABASE"
SENTINEL_CLIENT_ID = "38ada733-2629-4e15-ad41-aed5c962ea9b"
SENTINEL_CLIENT_SECRET = "43NE2pezayIKM9AMxRp84mKdSWiMvU6u"
