SUPABASE_URL = "https://ieodzygauglvdkendvmj.supabase.co"
SUPABASE_KEY = "sb_publishable_YS3LTJInGQZgxw0cZmTCZw_4rFz1Oaq"
OPENWEATHER_API_KEY = "2762051ad62d06f1d0fe146033c1c7c8"
SENTINEL_CLIENT_ID = "38ada733-2629-4e15-ad41-aed5c962ea9b"
SENTINEL_CLIENT_SECRET = "43NE2pezayIKM9AMxRp84mKdSWiMvU6u"

